import "./globals.css";
import "@radix-ui/themes/styles.css";
import './theme-config.css'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";
import { Container, Theme, ThemePanel } from '@radix-ui/themes'
import { Toaster } from 'sonner'
import QueryClientProvider from "./QueryClientProvider";


const inter = Inter({
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-inter'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <QueryClientProvider>
          <Theme appearance='dark' accentColor="jade">
            <Toaster position="bottom-right" theme="dark" richColors />
            <NavBar />
            <main className="p-5">
              <Container>
                {children}
              </Container>
            </main>
          </Theme>
        </QueryClientProvider>
      </body>
    </html>
  );
}
